<!-- MAIN PAGE -->
<a href="/">Main Page</a>

<?php if (count($flash) > 0): ?>
    <?php foreach ($flash as $messages): ?>
        <?php foreach ($messages as $message): ?>
            <div><?= htmlspecialchars($message) ?></div>
        <?php endforeach ?>
    <?php endforeach ?>
<?php endif ?>

<form action="/users/<?= htmlspecialchars($user['id']) ?>" method="post">
    <input type="hidden" name="_METHOD" value="PATCH">
    <div>
        <label>
            Name
            <input type="text" name="user[name]" value="<?= htmlspecialchars($user['name'] ?? '') ?>" required>
        </label>
        <?php if (isset($errors['name'])): ?>
            <?= $errors['name'] ?>
        <?php endif ?>
    </div>
    <div>
        <label>
            Email
            <input type="text" name="user[email]" value="<?= htmlspecialchars($user['email'] ?? '') ?>" required>
        </label>
        <?php if (isset($errors['email'])): ?>
            <?= $errors['email'] ?>
        <?php endif ?>
    </div>
    <div>
        <label>
            Password
            <input type="password" name="user[password]" required>
        </label>
        <?php if (isset($errors['password'])): ?>
            <div><?= $errors['password'] ?></div>
        <?php endif ?>
    </div>
    <div>
        <label>
            Password Confirmation
            <input type="password" name="user[passwordConfirmation]" required>
        </label>
        <?php if (isset($errors['passwordConfirmation'])): ?>
            <div><?= $errors['passwordConfirmation'] ?></div>
        <?php endif ?>
    </div>
    <input type="submit" value="Update">
</form>
