<!-- // https://ru.hexlet.io/courses/php-mvc/lessons/template/theory_unit -->
<!-- BEGIN -->
<table>
    <?php foreach ($users as $user) : ?>
        <tr>
            <td>
                <?= $user['id'] ?>
            </td>
            <td>
                <a href="/users/<?= $user['id'] ?>"><?= $user['firstName'] ?></a>
            </td>
        </tr>
    <?php endforeach ?>
</table>
<!-- END -->

<!-- https://ru.hexlet.io/courses/php-mvc/lessons/get-form/theory_unit -->
<!-- BEGIN -->
<form action="/users">
  <input type="search" name="term" value="<?= htmlspecialchars($term) ?>">
  <input type="submit" value="Search">
</form>

<?php foreach ($users as $user): ?>
  <div>
    <?= htmlspecialchars($user['firstName']) ?>
  </div>
<?php endforeach ?>
<!-- END -->
