<?php foreach ($users as $user): ?>
    <div>
        <?= htmlspecialchars($user) ?>
    </div>
<?php endforeach ?>

<!-- SEARCHING FORM -->
<form action="/users" method="GET">
    <input type="search" name="user" value="<?= htmlspecialchars($showRequest) ?>" required>
    <input type="submit" value="search">
</form>

<!-- RESULT -->
<?php foreach ($search as $find): ?>
    <div>
        <?= htmlspecialchars($find) ?>
    </div>
<?php endforeach ?>