<!-- // https://ru.hexlet.io/courses/php-mvc/lessons/template/theory_unit -->
<!-- BEGIN -->
<table>
    <?php foreach ($users as $user) : ?>
        <tr>
            <td>
                <?= $user['id'] ?>
            </td>
            <td>
                <a href="/users/<?= $user['id'] ?>"><?= $user['firstName'] ?></a>
            </td>
        </tr>
    <?php endforeach ?>
</table>
<!-- END -->